apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-website-deployment
spec:
    selector:
        matchLabels:
            app: nginx-website
    replicas: 1
    template:
        metadata:
            labels:
                app: nginx-website
        spec:
            containers:
              - name: nginx-website
                image: ashwindinesh/nginx-website
                imagePullPolicy: Never
                ports:
                  - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-service
spec:
    selector:
        app: nginx-website
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 80
        nodePort: 31000
    type: NodePort
